security:
    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt

    providers:
        app_in_memory_provider:
            memory:
                users:
                    patrick-mcdougle:
                        password: $2y$13$w5deQ4poYkBzsmOp48d5We7TIlNnSLuyv5h7N7zAKt/7VOQC48cWa
                        roles: [ROLE_ADMIN]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout:
                path: logout
                target: /
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: admin

                username_parameter: login_form[username]
                password_parameter: login_form[password]

                csrf_provider: security.csrf.token_manager
                csrf_parameter: login_form[_token]
                intention: login_form

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
