parameters:
#    parameter_name: value

services:
    login_form:
        class: AppBundle\Form\LoginFormType
        arguments: [@security.authentication_utils, @router]
        tags:
            - { name: form.type, alias: login_form }
